services:
  rest-api:
    build:
      context: './'
      dockerfile: dockerfile
    environment:
      - NODE_ENV=production
    env_file: ./.env
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db  
    command: ["wait-for-it", "db:3306", "--", "npm", "start"]

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin  
      MYSQL_DATABASE: RecetasApp  
    ports:
      - "3307:3306"  
    volumes:
      - mysql-data:/var/lib/mysql  # Persistencia de datos de MySQL

volumes:
  mysql-data:  # Define un volumen persistente para los datos de MySQL.
